name: CI
env:
  ICAPDOCKER_USERNAME: icapserviceaccount
  REPOSITORY: glasswallsolutions
  IMAGE: mvp-icap-service
  TAG: develop
on:
  push:
    branches: [ develop ]

jobs:

  build-push-docker-image:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Docker Login
      uses: docker/login-action@v1.6.0
      with:
        username: ${{ env.ICAPDOCKER_USERNAME }}
        password: ${{ secrets.ICAPDOCKERSECRET }}
    - name: Build and Push Docker Image
      run: |
        docker build -t ${{ env.REPOSITORY }}/${{ env.IMAGE }}:${{ env.TAG }}-${GITHUB_SHA::7} -t ${{ env.REPOSITORY }}/${{ env.IMAGE }}:${{ env.TAG }}-latest .
        docker push ${{ env.REPOSITORY }}/${{ env.IMAGE }}